name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20, 22]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: tools/cc-sdd/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: tools/cc-sdd
    
    - name: Run tests
      run: npm test
      working-directory: tools/cc-sdd
    
    - name: Build package
      run: npm run build
      working-directory: tools/cc-sdd
    
    - name: Test CLI
      run: node dist/cli.js --version
      working-directory: tools/cc-sdd

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: tools/cc-sdd/package-lock.json
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
      working-directory: tools/cc-sdd
    
    - name: Build package
      run: npm run build
      working-directory: tools/cc-sdd
    
    - name: Publish to NPM
      run: npm publish
      working-directory: tools/cc-sdd
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
